### ISSUE TITLE
Not a valid Arduino libray

### ISSUE THREAD

**Issue by SunboX** [albrdev/Sunrise#1]
If I download the library as Zip file and try to import it in Arduino IDE, it tells me, it's not a valid library. Can you please check why?

**Comment by albrdev** [comment]
This is a project I didn't have enough time to debug that much, but it looks like I forgot about the Arduino IDE property file (I used PlatformIO IDE). I made a quick property file (in master branch) which should resolve the issue.

**Comment by SunboX** [comment]
Thanks a lot 👍 I will try it tomorrow and let you know. If it still doesn't work,. I will figure it out. Have to wait for the sensor anyway, ordered it today from Driesen + Kern GmbH. Hopefully will get it next week.

**Comment by SunboX** [comment]
Can confirm, works as expected! :D Thanks a lot! Now I have to wait for the sensor itself ;)
